import type { NextPage } from 'next'
import DelphaiInterface from '../flow/delphaiInterface'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
    const [delphai, setDelphai] = useState<DelphaiInterface>();

    useEffect(() => {
        setDelphai(new DelphaiInterface());
    }, []);

    return (
        <div className={styles.container}>
        <Head>
            <title>Flow Wallet Error Repro</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
            Test
            </h1>
        </main>
        </div>
    )
}

export default Home
